name = "PolyOCP"
uuid = "486de887-2d28-4133-b065-860be2a859fb"
authors = ["Ruchuan Ou <ruchuan.ou@tuhh.de> and contributors"]
version = "0.1.0"

[deps]
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ParameterJuMP = "774612a8-9878-5177-865a-ca53ae2495f9"
PolyChaos = "8d666b04-775d-5f6e-b778-5ac7c70f65a3"
SparseArrayKit = "a9a3c162-d163-4c15-8926-b8794fbefed2"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Ipopt = "1.13.0"
JuMP = "1.29.3"
LinearAlgebra = "1.11.0"
ParameterJuMP = "0.4.1"
PolyChaos = "0.2.11"
SparseArrayKit = "0.4.1"
SpecialFunctions = "2.6.1"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
